### ISSUE TITLE
z-scores for original SNPs change a lot after imputation

### ISSUE THREAD

**Issue by xxxxuexiao** [statsleelab/gauss#1]
Thanks so much for your great work! I just found something strange when I looked at SNP z-scores before and after imputation.

Here is my original gwas. "a1" is the reference allele and effect allele.
![image](https://user-images.githubusercontent.com/120503144/219083072-24f0930a-785a-4841-997f-ea5554a46bc3.png)

Here are statistics for these originally existing SNPs after imputation.
![image](https://user-images.githubusercontent.com/120503144/219082724-6213da75-ba68-476b-bfbf-1a6093e83c92.png)

Take "rs12238997" as an example. "a1" and "a2" were flipped after imputation. However, z-scores are still negative (-0.8695652 before imputation and -0.8287 after imputation). Another example is "rs4951859". Its z-score changes from 1 before imputation to -0.1987 after imputation. Is it normal to get results like this?

FYI, here is my code to run dist() for gwas imputation.
![image](https://user-images.githubusercontent.com/120503144/219077199-5eaee082-ed44-4a0d-b1e8-eff8ce783d11.png)

Sorry to bother you, and thanks so much if you could help.

Best regards,
Xue

**Comment by dleelab** [comment]
Hi Xue,

Sorry for the late response. The input format of dist() function should be:

rsid chr bp a1 a2 z

Please remove the af1 column in your input data and run the dist function
again.  This will fix the problem.


Best,
Don
